version: "3"
services:
  redis:
    container_name: redis
    image: redis
  postgres:
    container_name: postgres
    restart: always
    image: mdillon/postgis:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
