version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - 3333:4000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      POSTGRES_URL: postgres://docker:docker@postgres:5432/docker
      REDIS_URL: redis://redis:6379
      JWT_SECRET: Not.Known.Secret.Word
      SESSION_SECRET: VerySecretKey
  redis:
    image: redis
  postgres:
    container_name: postgres
    restart: always
    image: mdillon/postgis:10-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
