version: "2"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: debug.Dockerfile
    env_file:
      - .env
    links:
      - redis:redis
      - postgres:postgres
    ports:
      - 3000
      - 3333:3000
      - 8080:8080
      - 9229:9229
  redis:
    image: redis
  postgres:
    restart: always
    image: mdillon/postgis:10-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker