version: "2"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/srv
    links:
      - postgres:postgres
    ports:
      - 3000
      - 3333:3000
  postgres:
    restart: always
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
